Repository webpack-contrib/uglifyjs-webpack-plugin, pull requests merged in 2018-04, with the labels that each got.

#271 >=, not =<
  README.md
Labels: priority: 4 (important), semver: Patch, severity: 5 (confusing), type: Bug, type: Documentation

#268 fix: don't handle invalid source map
  src/index.js
  src/utils/index.js
  test/__snapshots__/source-map-options.test.js.snap
  test/parallel-options.test.js
  test/source-map-options.test.js
  test/utils/index.test.js
Labels: pr_action: Review, priority: 3 (required), semver: Patch, severity: 3 (broken), type: Bug

#277 refactor: push each `warning` separately
  src/index.js
  test/__snapshots__/all-options.test.js.snap
Labels: pr_action: Review, priority: 5 (nice to have), semver: Patch, severity: 4 (inconvenient), type: Refactor

#276 perf: reduce memory usage
  src/index.js
Labels: pr_action: Review, priority: 4 (important), semver: Patch, severity: 3 (broken), type: Perf
