Repository webpack-contrib/uglifyjs-webpack-plugin, pull requests merged in 2018-02, with the labels that each got.

#229 feat(minify): add missing `toplevel`, `nameCache`, `keep_classnames`, `keep_fnames` and `safari10` options (`uglifyOptions`)
  README.md
  src/uglify/minify.js
  test/__snapshots__/uglify-options.test.js.snap
  test/uglify-options.test.js
Labels: semver: Minor, status: Approved, type: Feature

#238 fix(index): `tapable` deprecation warnings (`webpack >= v4.0.0`)
  src/index.js
Labels: pr_action: Review, priority: 3 (required), semver: Patch, severity: 4 (inconvenient), type: Bug

#239 fix(package): add `webpack >= v4.0.0` (`peerDependencies`)
  package.json
Labels: semver: Patch, status: Approved, type: Bug

#242 fix(index): typo `buildMobule` => `buildModule`
  src/index.js
Labels: semver: Patch, status: Approved, type: Bug

#243 perf(index): use `md4` instead `md5` for content hasing
  src/index.js
  test/__snapshots__/cache-options.test.js.snap
Labels: semver: Patch, status: Approved, type: Perf
