Repository webpack-contrib/uglifyjs-webpack-plugin, pull requests merged in 2018-03, with the labels that each got.

#249 fix(index): correct `[name].js.LICENSE` file path (`options.extractComments`)
  src/index.js
  test/__snapshots__/extract-comments-options.test.js.snap
  test/extract-comments-options.test.js
Labels: semver: Patch, status: Approved, type: Bug

#251 fix(index): relax default in asset names `{RegExp}` (`options.test`)
  src/index.js
  test/__snapshots__/test.test.js.snap
  test/fixtures/async-import-export/async-dep.js
  test/fixtures/async-import-export/entry.js
  test/fixtures/entry.mjs
  test/fixtures/import-export/async-dep.js
  test/test.test.js
Labels: pr_action: Review, priority: 4 (important), semver: Patch, severity: 3 (broken), type: Bug

#253 fix(package): update`cacache` v10.0.1...10.0.4 (`dependencies`)
  package.json
Labels: semver: Patch, status: Approved, type: Bug

#255 fix(package): update `schema-utils` v0.4.3...0.4.5 (`dependencies`)
  package-lock.json
  package.json
  test/__snapshots__/invalid-options.test.js.snap
Labels: semver: Patch, status: Approved, type: Bug

#258 test(invalid-options): update snapshot
  test/__snapshots__/invalid-options.test.js.snap
Labels: semver: Patch, status: Approved, type: Test

#259 fix(index): correct default asset name `{RegExp}` (`options.test`)
  src/index.js
Labels: semver: Patch, status: Approved, type: Bug
